apiVersion: v1
kind: ConfigMap
metadata:
  name: shared-config
  namespace: url-shortener
data:
  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5432"
  POSTGRES_DB: urlshortener
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  RABBITMQ_HOST: rabbitmq
  RABBITMQ_PORT: "5672"
  MONGODB_HOST: mongodb
  MONGODB_PORT: "27017"
---
apiVersion: v1
kind: Secret
metadata:
  name: shared-secrets
  namespace: url-shortener
type: Opaque
stringData:
  POSTGRES_USER: urlshortener
  POSTGRES_PASSWORD: urlshortener
  RABBITMQ_USER: urlshortener
  RABBITMQ_PASS: urlshortener
  MONGODB_USER: urlshortener
  MONGODB_PASS: urlshortener
  DJANGO_SECRET_KEY: local-dev-secret-key-change-in-prod
